"""
Training loop and metrics for the cased-hole forward operator (M5c).

Mirrors ``models/train.py`` (the M2 open-hole surrogate) but over the cased-hole
feature set, with a masked loss so the ``NaN`` sentinels of an absent mode never
contribute. :func:`resolution_transfer_error` is the metric that only an
operator can post: predict on a refined frequency grid and compare against the
model's own prediction at the shared nodes.
"""

from __future__ import annotations

import numpy as np
import torch
from torch.utils.data import DataLoader, Dataset

from sonic_ml.determinism import seed_everything
from sonic_ml.loader import DatasetBundle
from sonic_ml.models.cased import (
    CasedForwardOperator,
    TrainedCasedOperator,
    cased_features,
    normalized_coords,
)
from sonic_ml.models.dataset import SlownessNormalizer
from sonic_ml.models.losses import masked_slowness_loss
from sonic_ml.normalize import Standardizer
from sonic_ml.split import DataSplit, stratified_split

#: Metres per foot -- slowness in s/m becomes us/ft via ``s * 0.3048 * 1e6``.
_M_PER_FT: float = 0.3048


class CasedDataset(Dataset):
    """
    Tensor view of a cased-hole bundle for operator training.

    Each item is ``(x, target, mask)``:

    * ``x`` -- standardized active features, shape ``(n_active,)``, float32.
    * ``target`` -- per-mode standardized slowness, shape ``(M, F)``, float32
      (masked entries zeroed).
    * ``mask`` -- finite-slowness mask, shape ``(M, F)``, bool.

    Parameters
    ----------
    bundle : DatasetBundle
        A cased-hole dataset (schema v4).
    indices : ndarray of int
        Sample indices to include.
    feature_std : Standardizer
        Fitted on the *training* features.
    slowness_norm : SlownessNormalizer
        Fitted on the *training* slowness.
    """

    def __init__(
        self,
        bundle: DatasetBundle,
        indices: np.ndarray,
        feature_std: Standardizer,
        slowness_norm: SlownessNormalizer,
    ) -> None:
        idx = np.asarray(indices, dtype=int)
        features, _ = cased_features(bundle)
        x = feature_std.transform(features[idx])
        slow = bundle.slowness[idx]
        mask = np.isfinite(slow)
        target = np.nan_to_num(slowness_norm.transform(slow), nan=0.0)

        self.x = torch.as_tensor(x, dtype=torch.float32)
        self.target = torch.as_tensor(target, dtype=torch.float32)
        self.mask = torch.as_tensor(mask, dtype=torch.bool)

    def __len__(self) -> int:
        return int(self.x.shape[0])

    def __getitem__(
        self, index: int
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        return self.x[index], self.target[index], self.mask[index]


def train_cased_operator(
    bundle: DatasetBundle,
    *,
    split: DataSplit | None = None,
    epochs: int = 60,
    batch_size: int = 32,
    lr: float = 3.0e-3,
    backbone: str = "fno",
    width: int = 32,
    n_fourier_modes: int = 16,
    depth: int = 4,
    latent: int = 64,
    seed: int = 0,
    device: str = "cpu",
) -> tuple[TrainedCasedOperator, list[float]]:
    """
    Train the cased-hole forward operator on a schema-v4 bundle.

    Parameters
    ----------
    bundle : DatasetBundle
        A cased-hole dataset.
    split : DataSplit or None
        Train/val/test split; ``None`` builds a regime-stratified one. A cased
        dataset generated by ``generate_cased_dataset`` is fast-formation only,
        so that reduces to a reproducible random split.
    epochs, batch_size, lr : training hyperparameters.
    backbone : {"fno", "deeponet"}, default "fno"
        Operator primitive to train.
    width, n_fourier_modes, depth, latent : architecture hyperparameters.
    seed : int, default 0
        Master seed.
    device : str, default "cpu"

    Returns
    -------
    trained : TrainedCasedOperator
    history : list of float
        Mean training loss per epoch.
    """
    seed_everything(seed)
    if split is None:
        split = stratified_split(bundle, seed=seed)

    features, feature_names = cased_features(bundle)
    feature_std = Standardizer.fit(features[split.train], feature_names)
    slowness_norm = SlownessNormalizer.fit(bundle.slowness[split.train])
    train_ds = CasedDataset(bundle, split.train, feature_std, slowness_norm)

    dev = torch.device(device)
    model = CasedForwardOperator(
        feature_std.n_active,
        bundle.n_modes,
        backbone=backbone,
        width=width,
        n_fourier_modes=n_fourier_modes,
        depth=depth,
        latent=latent,
    ).to(dev)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    coords = torch.as_tensor(
        normalized_coords(bundle.freq, float(bundle.freq[0]), float(bundle.freq[-1])),
        dtype=torch.float32,
    ).to(dev)

    generator = torch.Generator()
    generator.manual_seed(seed)
    loader = DataLoader(
        train_ds,
        batch_size=batch_size,
        shuffle=True,
        num_workers=0,
        generator=generator,
    )

    history: list[float] = []
    for _ in range(epochs):
        model.train()
        total = 0.0
        n_batches = 0
        for x, target, mask in loader:
            x, target, mask = x.to(dev), target.to(dev), mask.to(dev)
            optimizer.zero_grad()
            pred = model(x, coords)
            loss = masked_slowness_loss(pred, target, mask)
            loss.backward()
            optimizer.step()
            total += float(loss.detach())
            n_batches += 1
        history.append(total / max(n_batches, 1))

    trained = TrainedCasedOperator(
        model.eval(),
        feature_std,
        slowness_norm,
        feature_names,
        bundle.mode_names,
        bundle.freq,
    )
    return trained, history


def slowness_mae_us_per_ft(
    trained: TrainedCasedOperator,
    bundle: DatasetBundle,
    indices: np.ndarray,
) -> float:
    """
    Mean absolute slowness error in us/ft over finite target entries.

    Parameters
    ----------
    trained : TrainedCasedOperator
    bundle : DatasetBundle
    indices : ndarray of int
        Samples to score (e.g. a held-out split).

    Returns
    -------
    float
        MAE in us/ft; ``nan`` if no finite target entries are selected.
    """
    idx = np.asarray(indices, dtype=int)
    features, _ = cased_features(bundle)
    pred = trained.predict(features[idx])
    truth = bundle.slowness[idx]
    mask = np.isfinite(truth)
    if not mask.any():
        return float("nan")
    err = np.abs(pred[mask] - truth[mask])
    return float(err.mean() * _M_PER_FT * 1.0e6)


def resolution_transfer_error(
    trained: TrainedCasedOperator,
    bundle: DatasetBundle,
    indices: np.ndarray,
    *,
    factor: int = 2,
) -> float:
    """
    Relative self-consistency of the operator on a refined frequency grid.

    Predicts on a grid ``factor``-times finer than the training grid (built so
    the training nodes are a strict subset) and compares against the prediction
    on the training grid at those shared nodes. A point network cannot be
    evaluated this way at all; for an operator this measures how stable the
    learned map is under re-gridding.

    Parameters
    ----------
    trained : TrainedCasedOperator
    bundle : DatasetBundle
    indices : ndarray of int
        Samples to evaluate.
    factor : int, default 2
        Refinement factor; must be ``>= 2``.

    Returns
    -------
    float
        ``||fine[shared] - coarse|| / ||coarse||``.
    """
    if factor < 2:
        raise ValueError(f"factor must be >= 2, got {factor}")
    idx = np.asarray(indices, dtype=int)
    features, _ = cased_features(bundle)
    coarse = np.asarray(bundle.freq, dtype=float)
    # A linspace of factor*(n-1)+1 points contains every coarse node exactly.
    fine = np.linspace(coarse[0], coarse[-1], factor * (coarse.size - 1) + 1)

    on_coarse = trained.predict(features[idx])
    on_fine = trained.predict(features[idx], freq=fine)[..., ::factor]
    denom = np.linalg.norm(on_coarse)
    if denom == 0.0:  # pragma: no cover - degenerate
        return float("nan")
    return float(np.linalg.norm(on_fine - on_coarse) / denom)
