"""
Fetch third-party real-world log files for the optional integration tests.

Everything else in the test suite runs on synthetics with planted answers, which
is what makes those tests assertable -- and also what limits them. A synthetic
gather is generated by the same forward model the code under test assumes, so it
can never surprise the reader with a convention it did not anticipate. Files
written by other software can.

**Nothing here is vendored.** The datasets are downloaded on demand into a
git-ignored directory and verified against a recorded SHA-256. That is a
deliberate licensing decision, not a convenience: the files below are published
by third parties under their own terms -- one of them carries an explicit
third-party copyright notice in its own header -- and redistributing them inside
this repository would require permissions we do not have. Pointing at a URL
requires none.

Usage
-----
::

    python scripts/fetch_real_data.py --list          # registry + licences
    python scripts/fetch_real_data.py --fetch all     # download + verify
    python scripts/fetch_real_data.py --verify        # re-check checksums

Then ``pytest tests/test_real_data.py`` picks the files up automatically; without
them those tests skip with a pointer to this script. The destination defaults to
``tests/data/real/`` and can be overridden with ``FWAP_REAL_DATA_DIR``.

Scope note
----------
This file used to say that no openly redistributable full-waveform sonic gather
was known to exist. **That was false**, and ``iodp_u1347a_dsi`` below is the
counterexample: an eight-receiver Schlumberger DSI run published by the
Lamont-Doherty Borehole Research Group under CC0. What had actually been
established was that none had been *found*, which is a different claim, and one
that goes stale the moment somebody looks again.

The limit that remains is narrower and worth stating precisely: the registry now
reaches a real gather, but only one hole of one tool, and the ``sonic_ml``
results are still measured against the forward model that generated their
training data. One real gather bounds how wrong the *processing* can be; it does
not turn a synthetic identifiability study into a field measurement.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import urllib.request
import zipfile
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

#: Environment variable overriding where fetched files are stored.
DATA_DIR_ENV: str = "FWAP_REAL_DATA_DIR"

#: Default destination, relative to the repository root.
DEFAULT_DATA_DIR: Path = Path("tests") / "data" / "real"

#: Read size for streaming downloads and hashing.
_CHUNK = 1 << 16


@dataclass(frozen=True)
class RealDataset:
    """
    One third-party file the integration tests can use.

    Attributes
    ----------
    name : str
        Registry key, used on the command line.
    filename : str
        Name the file is saved under in the data directory.
    url : str
        Stable public download URL.
    sha256 : str
        Expected SHA-256 of the downloaded bytes. A mismatch is an error, not a
        warning: silently testing against different content than the assertions
        were written for is worse than not testing at all.
    kind : {"las", "segy", "dlis"}
        Which reader the file exercises.
    what_it_tests : str
        The specific failure mode this file can catch that a synthetic cannot.
    provenance : str
        Where the data came from.
    licence : str
        Licensing situation, including anything that constrains redistribution.
    member : str or None
        Path *inside* the downloaded file when it is a zip archive, for
        publishers who only distribute a whole deposit. ``None`` when the URL
        serves the data file directly.
    member_sha256 : str or None
        Expected SHA-256 of the extracted member. Recorded separately because a
        zip can be recompressed -- changing the archive's digest while leaving
        the member's untouched -- so this is the digest the assertions actually
        depend on.
    """

    name: str
    filename: str
    url: str
    sha256: str
    kind: str
    what_it_tests: str
    provenance: str
    licence: str
    member: str | None = None
    member_sha256: str | None = None


#: The registry. Add an entry to make a new file available to the tests.
DATASETS: tuple[RealDataset, ...] = (
    RealDataset(
        name="kgs_las",
        filename="kgs_1001178549.las",
        url=(
            "https://raw.githubusercontent.com/kinverarity1/lasio/main/"
            "tests/examples/1001178549.las"
        ),
        sha256="f4c364a7f7bd4b8429ef0961741efcd61402e2ef7267f6c2005dacb805d6527c",
        kind="las",
        what_it_tests=(
            "A real, awkward LAS: WRAP=YES multi-line records, 26 curves with "
            "non-standard service-company mnemonics, vendor comment blocks "
            "before the version section, and API curve codes. Our own writer "
            "emits none of these, so a round-trip test through write_las cannot "
            "reach any of it."
        ),
        provenance=(
            "Kansas Geological Survey public well-log archive; AMOCO "
            "'Collingwood 1-28', Stanton County, Kansas (UWI 15-187-20743). "
            "Mirrored in the lasio test corpus, which is the URL used here."
        ),
        licence=(
            "lasio is MIT (Kent Inverarity and contributors). The log itself is "
            "published by the KGS, and the file header additionally carries "
            "'DATA COPYRIGHT - RILEYS DATASHARE INTERNATIONAL'. That notice is "
            "precisely why this file is fetched rather than vendored."
        ),
    ),
    RealDataset(
        name="forge_dsi_las",
        filename="forge_D5RL-00187_ME-ESW1_DSI.las",
        url=(
            "https://gdr.openei.org/files/1006/"
            "D5RL-00187_University%20of%20%20Utah_ME-ESW1_Run1_DSI%20Sonic.las"
        ),
        sha256="30cbc94a3596b6ccb061398fbb832793012795b360d5a452210696adf719e3ad",
        kind="las",
        what_it_tests=(
            "The first *sonic* log in the registry, and the first real "
            "service-company reference picks. A Schlumberger DSI run over "
            "2150.5-7569.0 ft at 0.5 ft, carrying DTCO and DTSM alongside the "
            "per-mode coherence peaks (CHRP, CHR1, CHR2) the tool's own "
            "slowness-time processing produced. That makes it scoreable: the "
            "package's picks can be compared against a vendor's on identical "
            "depths, which no synthetic can provide. The KGS log tests LAS "
            "*parsing* oddities; this one tests whether the processing is right."
        ),
        provenance=(
            "Utah FORGE, well ME-ESW1 (the 58-32 monitor well), University of "
            "Utah / DOE Geothermal Data Repository submission 1006. Logged "
            "15-Sep-2017 by Schlumberger. The companion DLIS in the same "
            "submission holds the per-receiver waveforms this file is the "
            "processed export of: DTCO and DTSM agree between the two to "
            "5e-5 us/ft over all 10 837 common depths, so they are the same "
            "processing run.\n"
            "CHECKSUM CAVEAT: the SHA-256 above was computed from a copy "
            "obtained through a mirror, because gdr.openei.org was not "
            "reachable from the session that added this entry. It has NOT been "
            "confirmed against the canonical URL. The first successful fetch "
            "should verify it and correct this note."
        ),
        licence=(
            "CC BY 4.0. DOE Geothermal Technologies Office data published "
            "through the Geothermal Data Repository is openly licensed, so this "
            "file is redistributable as well as fetchable -- unlike the KGS log "
            "above. It is still fetched rather than vendored, for consistency "
            "with the no-vendoring rule the data directory enforces."
        ),
    ),
    RealDataset(
        name="iodp_u1347a_dsi",
        filename="iodp_324-U1347A_logging_data.zip",
        url=(
            "https://zenodo.org/records/3939555/files/"
            "324-U1347A_logging_data.zip?download=1"
        ),
        sha256="703b341cc2902c4a73727652c23dd4ea264f9817314bc08e83660a5884334cbd",
        member=("324-U1347A_logging_data/Sonic Waveform Data/324-U1347A_mono_p1.bin"),
        member_sha256=(
            "8cc7c82f90f0d630d72cfb51a00e2a8de2ec71b376dae0158f11077a3ea8154f"
        ),
        kind="ldeo",
        what_it_tests=(
            "The registry's first real full-waveform gather, and the first "
            "thing here that can contradict the sonic processing rather than "
            "only the parsers. 1307 depths of an eight-receiver Schlumberger "
            "DSI monopole run, 512 samples at 10 us on 0.1524 m receiver "
            "spacing -- which is `ArrayGeometry`'s default geometry, arrived at "
            "independently. Every slowness this package reports is otherwise "
            "measured against the forward model that generated its own input; "
            "these gathers were not generated by anything in this repository. "
            "The deposit also carries `std-proc.dlis` with the vendor's own DT "
            "curves over the same depths, so the picks are scoreable against a "
            "service company's rather than against a synthetic's planted answer."
        ),
        provenance=(
            "IODP Expedition 324, Hole U1347A (Shatsky Rise, TAMU Massif, NW "
            "Pacific), logged 30-Sep/1-Oct-2009. Published by the Lamont-Doherty "
            "Earth Observatory Borehole Research Group via its LogDB mirror on "
            "Zenodo, record 3939555. `mono_p1.bin` is the monopole P&S pass 1; "
            "the deposit also holds the downlog, pass 2, upper and lower dipole "
            "and cross-dipole, plus three original DSI DLIS runs.\n"
            "SIZE: the deposit is 578 MB, because Zenodo publishes the hole's "
            "whole logging archive as one file. The member used here is 21 MB "
            "of it.\n"
            "CHECKSUM CAVEAT: both digests above were computed from a copy that "
            "did not come down the canonical URL -- zenodo.org was blocked from "
            "the session that added this entry, so the file arrived by another "
            "route. The URL's shape is inferred from Zenodo's standard file "
            "layout and has NOT been exercised. The first successful fetch "
            "should confirm both, and correct this note.\n"
            "GEOMETRY: transmitter-to-receiver offsets are in neither the "
            "waveform export nor the DLIS it came from. Receiver *spacing* is "
            "0.1524 m from the archive's own file description; the absolute "
            "offset has to come from the DSI specification. `plans/roadmap.md` "
            "F.5 records how the equivalent question was settled for another "
            "hole -- take the offsets from the tool spec, then test them "
            "against first-break moveout across the array."
        ),
        licence=(
            "CC0 1.0 Universal (public-domain dedication), as stated on the "
            "Zenodo record. That is the first entry here that could lawfully be "
            "vendored rather than fetched -- the no-vendoring rule at the top of "
            "this file is a licensing rule, and CC0 removes the reason for it. "
            "It is still fetched, because 578 MB does not belong in a git "
            "repository; the reason is now size rather than permission.\n"
            "Note the licence is asserted by the archive, which is not the party "
            "that acquired the data: Schlumberger logged the hole under contract "
            "to the drilling programme, and LDEO publishes it. That is the "
            "ordinary arrangement for scientific ocean drilling, and it is "
            "recorded here rather than smoothed over."
        ),
    ),
    RealDataset(
        name="segyio_small",
        filename="segyio_small.sgy",
        url=(
            "https://raw.githubusercontent.com/equinor/segyio/master/"
            "test-data/small.sgy"
        ),
        sha256="e939ed45a8258f1fbaf3c21ca83f54369c4c4def79384b4cb0fc069a4eb1a191",
        kind="segy",
        what_it_tests=(
            "A SEG-Y written by *other* software. Our SEG-Y tests otherwise "
            "read back what fwap.write_segy produced, which cannot catch a "
            "disagreement about header layout, sample format or byte order -- "
            "the reader and writer would simply share the mistake."
        ),
        provenance=(
            "The segyio project's test corpus (Equinor). Synthetic content: it "
            "is a small regular cube, not a shot gather, so its trace headers "
            "carry no meaningful source-receiver offsets."
        ),
        licence=(
            "segyio is LGPL-licensed and its README solicits test files under "
            "free licences. Fetched, not vendored."
        ),
    ),
)


def data_dir() -> Path:
    """
    Resolve the directory fetched datasets live in.

    Returns
    -------
    pathlib.Path
        ``$FWAP_REAL_DATA_DIR`` if set, else ``tests/data/real`` under the
        repository root.
    """
    override = os.environ.get(DATA_DIR_ENV)
    if override:
        return Path(override).expanduser()
    return Path(__file__).resolve().parent.parent / DEFAULT_DATA_DIR


def find(name: str) -> RealDataset:
    """
    Look up a dataset by registry name.

    Raises
    ------
    KeyError
        If ``name`` is not registered.
    """
    for dataset in DATASETS:
        if dataset.name == name:
            return dataset
    known = ", ".join(d.name for d in DATASETS)
    raise KeyError(f"unknown dataset {name!r}; known datasets: {known}")


def sha256_of(path: Path) -> str:
    """Return the hex SHA-256 digest of a file, read in chunks."""
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        while chunk := handle.read(_CHUNK):
            digest.update(chunk)
    return digest.hexdigest()


def local_path(dataset: RealDataset, directory: Path | None = None) -> Path:
    """Where ``dataset`` is (or would be) stored locally."""
    return (directory or data_dir()) / dataset.filename


def verify(dataset: RealDataset, directory: Path | None = None) -> bool:
    """
    Check a already-downloaded dataset against its recorded checksum.

    Returns
    -------
    bool
        ``True`` if the file exists and its digest matches.
    """
    path = local_path(dataset, directory)
    return path.is_file() and sha256_of(path) == dataset.sha256


def fetch(
    dataset: RealDataset,
    directory: Path | None = None,
    *,
    force: bool = False,
) -> Path:
    """
    Download one dataset and verify its checksum.

    Parameters
    ----------
    dataset : RealDataset
    directory : pathlib.Path or None
        Destination directory; defaults to :func:`data_dir`.
    force : bool, default False
        Re-download even if a verified copy is already present.

    Returns
    -------
    pathlib.Path
        Path to the verified local file.

    Raises
    ------
    OSError
        If the download fails.
    ValueError
        If the downloaded bytes do not match the recorded SHA-256. The bad file
        is removed rather than left to be silently tested against.
    """
    destination = directory or data_dir()
    destination.mkdir(parents=True, exist_ok=True)
    path = local_path(dataset, destination)

    if path.is_file() and not force:
        if verify(dataset, destination):
            return path
        raise ValueError(
            f"{path} exists but its checksum does not match the registry; "
            "re-run with --force to replace it"
        )

    with urllib.request.urlopen(dataset.url) as response:  # noqa: S310
        payload = response.read()
    path.write_bytes(payload)

    digest = sha256_of(path)
    if digest != dataset.sha256:
        path.unlink(missing_ok=True)
        raise ValueError(
            f"checksum mismatch for {dataset.name}: expected {dataset.sha256}, "
            f"got {digest}. The upstream file may have changed; do not update "
            "the registry hash without checking what changed."
        )
    return path


def extract_member(
    dataset: RealDataset,
    directory: Path | None = None,
    *,
    force: bool = False,
) -> Path:
    """
    Extract a zip-archived dataset's member and verify its own checksum.

    Publishers who release a whole deposit as one file leave the data one level
    down. This unpacks that one member next to the archive, so a test opens an
    ordinary path rather than teaching itself about zip layout.

    Parameters
    ----------
    dataset : RealDataset
        Must have :attr:`~RealDataset.member` set.
    directory : pathlib.Path or None
        Where the archive lives; defaults to :func:`data_dir`.
    force : bool, default False
        Re-extract even if a verified copy is already present.

    Returns
    -------
    pathlib.Path
        The extracted member.

    Raises
    ------
    ValueError
        If the dataset has no member, the archive is absent, the member is
        missing from it, or the extracted bytes do not match
        :attr:`~RealDataset.member_sha256`.
    """
    if dataset.member is None:
        raise ValueError(f"{dataset.name} is not an archive with a member")

    destination = directory or data_dir()
    archive = local_path(dataset, destination)
    if not archive.is_file():
        raise ValueError(
            f"{archive} is not present; fetch it with "
            f"`python scripts/fetch_real_data.py --fetch {dataset.name}`"
        )

    out = destination / (dataset.filename + ".member" + Path(dataset.member).suffix)
    if out.is_file() and not force:
        if dataset.member_sha256 is None or sha256_of(out) == dataset.member_sha256:
            return out

    with zipfile.ZipFile(archive) as zf:
        try:
            payload = zf.read(dataset.member)
        except KeyError as exc:
            raise ValueError(
                f"{archive} does not contain {dataset.member!r}; the upstream "
                "archive layout may have changed"
            ) from exc
    out.write_bytes(payload)

    if dataset.member_sha256 is not None:
        digest = sha256_of(out)
        if digest != dataset.member_sha256:
            out.unlink(missing_ok=True)
            raise ValueError(
                f"member checksum mismatch for {dataset.name}: expected "
                f"{dataset.member_sha256}, got {digest}"
            )
    return out


def format_registry() -> str:
    """Render the registry, licences included, as human-readable text."""
    lines: list[str] = []
    for dataset in DATASETS:
        present = "present" if verify(dataset) else "not fetched"
        lines.append(f"{dataset.name}  [{dataset.kind}]  ({present})")
        lines.append(f"  file      : {dataset.filename}")
        if dataset.member is not None:
            lines.append(f"  member    : {dataset.member}")
        lines.append(f"  url       : {dataset.url}")
        lines.append(f"  tests     : {dataset.what_it_tests}")
        lines.append(f"  provenance: {dataset.provenance}")
        lines.append(f"  licence   : {dataset.licence}")
        lines.append("")
    lines.append(f"destination: {data_dir()}  (git-ignored; never committed)")
    return "\n".join(lines)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Fetch third-party real-world log files for the optional "
            "integration tests. Files are downloaded, never vendored."
        )
    )
    parser.add_argument(
        "--list", action="store_true", help="show the registry and licences"
    )
    parser.add_argument(
        "--fetch",
        metavar="NAME",
        help="dataset to download, or 'all'",
    )
    parser.add_argument(
        "--verify", action="store_true", help="re-check checksums of local files"
    )
    parser.add_argument(
        "--force", action="store_true", help="re-download even if present"
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """
    Command-line entry point.

    Returns
    -------
    int
        ``0`` on success, ``1`` if a fetch or verification failed.
    """
    args = _build_parser().parse_args(argv)

    if args.verify:
        failed = False
        for dataset in DATASETS:
            ok = verify(dataset)
            print(f"{'OK  ' if ok else 'MISS'}  {dataset.name}")
            failed |= not ok
        return 1 if failed else 0

    if args.fetch:
        targets = DATASETS if args.fetch == "all" else (find(args.fetch),)
        for dataset in targets:
            try:
                path = fetch(dataset, force=args.force)
            except (OSError, ValueError) as exc:
                print(f"FAILED {dataset.name}: {exc}")
                return 1
            print(f"fetched {dataset.name} -> {path}")
            if dataset.member is not None:
                try:
                    member = extract_member(dataset, force=args.force)
                except ValueError as exc:
                    print(f"FAILED {dataset.name} (member): {exc}")
                    return 1
                print(f"  extracted {dataset.member} -> {member}")
        print("\nThese files are third-party and git-ignored. Do not commit them.")
        return 0

    print(format_registry())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
