"""
Fetch third-party real-world log files for the optional integration tests.

Everything else in the test suite runs on synthetics with planted answers, which
is what makes those tests assertable -- and also what limits them. A synthetic
gather is generated by the same forward model the code under test assumes, so it
can never surprise the reader with a convention it did not anticipate. Files
written by other software can.

**Nothing here is vendored.** The datasets are downloaded on demand into a
git-ignored directory and verified against a recorded SHA-256. That is a
deliberate licensing decision, not a convenience: the files below are published
by third parties under their own terms -- one of them carries an explicit
third-party copyright notice in its own header -- and redistributing them inside
this repository would require permissions we do not have. Pointing at a URL
requires none.

Usage
-----
::

    python scripts/fetch_real_data.py --list          # registry + licences
    python scripts/fetch_real_data.py --fetch all     # download + verify
    python scripts/fetch_real_data.py --verify        # re-check checksums

Then ``pytest tests/test_real_data.py`` picks the files up automatically; without
them those tests skip with a pointer to this script. The destination defaults to
``tests/data/real/`` and can be overridden with ``FWAP_REAL_DATA_DIR``.

Scope note
----------
Neither dataset below is a full-waveform sonic gather, because no openly
redistributable one is known to exist -- full-waveform sonic data is almost
always proprietary. That gap is the single biggest limit on what this repository
can claim: every quantitative result, ``sonic_ml``'s included, is currently
measured against the same forward model that generated its data. Adding a real
sonic gather here is a one-entry change to :data:`DATASETS`, and it would do more
for confidence in this package than any amount of further synthetic work.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import urllib.request
from collections.abc import Sequence
from dataclasses import dataclass
from pathlib import Path

#: Environment variable overriding where fetched files are stored.
DATA_DIR_ENV: str = "FWAP_REAL_DATA_DIR"

#: Default destination, relative to the repository root.
DEFAULT_DATA_DIR: Path = Path("tests") / "data" / "real"

#: Read size for streaming downloads and hashing.
_CHUNK = 1 << 16


@dataclass(frozen=True)
class RealDataset:
    """
    One third-party file the integration tests can use.

    Attributes
    ----------
    name : str
        Registry key, used on the command line.
    filename : str
        Name the file is saved under in the data directory.
    url : str
        Stable public download URL.
    sha256 : str
        Expected SHA-256 of the downloaded bytes. A mismatch is an error, not a
        warning: silently testing against different content than the assertions
        were written for is worse than not testing at all.
    kind : {"las", "segy", "dlis"}
        Which reader the file exercises.
    what_it_tests : str
        The specific failure mode this file can catch that a synthetic cannot.
    provenance : str
        Where the data came from.
    licence : str
        Licensing situation, including anything that constrains redistribution.
    """

    name: str
    filename: str
    url: str
    sha256: str
    kind: str
    what_it_tests: str
    provenance: str
    licence: str


#: The registry. Add an entry to make a new file available to the tests.
DATASETS: tuple[RealDataset, ...] = (
    RealDataset(
        name="kgs_las",
        filename="kgs_1001178549.las",
        url=(
            "https://raw.githubusercontent.com/kinverarity1/lasio/main/"
            "tests/examples/1001178549.las"
        ),
        sha256="f4c364a7f7bd4b8429ef0961741efcd61402e2ef7267f6c2005dacb805d6527c",
        kind="las",
        what_it_tests=(
            "A real, awkward LAS: WRAP=YES multi-line records, 26 curves with "
            "non-standard service-company mnemonics, vendor comment blocks "
            "before the version section, and API curve codes. Our own writer "
            "emits none of these, so a round-trip test through write_las cannot "
            "reach any of it."
        ),
        provenance=(
            "Kansas Geological Survey public well-log archive; AMOCO "
            "'Collingwood 1-28', Stanton County, Kansas (UWI 15-187-20743). "
            "Mirrored in the lasio test corpus, which is the URL used here."
        ),
        licence=(
            "lasio is MIT (Kent Inverarity and contributors). The log itself is "
            "published by the KGS, and the file header additionally carries "
            "'DATA COPYRIGHT - RILEYS DATASHARE INTERNATIONAL'. That notice is "
            "precisely why this file is fetched rather than vendored."
        ),
    ),
    RealDataset(
        name="forge_dsi_las",
        filename="forge_D5RL-00187_ME-ESW1_DSI.las",
        url=(
            "https://gdr.openei.org/files/1006/"
            "D5RL-00187_University%20of%20%20Utah_ME-ESW1_Run1_DSI%20Sonic.las"
        ),
        sha256="30cbc94a3596b6ccb061398fbb832793012795b360d5a452210696adf719e3ad",
        kind="las",
        what_it_tests=(
            "The first *sonic* log in the registry, and the first real "
            "service-company reference picks. A Schlumberger DSI run over "
            "2150.5-7569.0 ft at 0.5 ft, carrying DTCO and DTSM alongside the "
            "per-mode coherence peaks (CHRP, CHR1, CHR2) the tool's own "
            "slowness-time processing produced. That makes it scoreable: the "
            "package's picks can be compared against a vendor's on identical "
            "depths, which no synthetic can provide. The KGS log tests LAS "
            "*parsing* oddities; this one tests whether the processing is right."
        ),
        provenance=(
            "Utah FORGE, well ME-ESW1 (the 58-32 monitor well), University of "
            "Utah / DOE Geothermal Data Repository submission 1006. Logged "
            "15-Sep-2017 by Schlumberger. The companion DLIS in the same "
            "submission holds the per-receiver waveforms this file is the "
            "processed export of: DTCO and DTSM agree between the two to "
            "5e-5 us/ft over all 10 837 common depths, so they are the same "
            "processing run.\n"
            "CHECKSUM CAVEAT: the SHA-256 above was computed from a copy "
            "obtained through a mirror, because gdr.openei.org was not "
            "reachable from the session that added this entry. It has NOT been "
            "confirmed against the canonical URL. The first successful fetch "
            "should verify it and correct this note."
        ),
        licence=(
            "CC BY 4.0. DOE Geothermal Technologies Office data published "
            "through the Geothermal Data Repository is openly licensed, so this "
            "file is redistributable as well as fetchable -- unlike the KGS log "
            "above. It is still fetched rather than vendored, for consistency "
            "with the no-vendoring rule the data directory enforces."
        ),
    ),
    RealDataset(
        name="segyio_small",
        filename="segyio_small.sgy",
        url=(
            "https://raw.githubusercontent.com/equinor/segyio/master/"
            "test-data/small.sgy"
        ),
        sha256="e939ed45a8258f1fbaf3c21ca83f54369c4c4def79384b4cb0fc069a4eb1a191",
        kind="segy",
        what_it_tests=(
            "A SEG-Y written by *other* software. Our SEG-Y tests otherwise "
            "read back what fwap.write_segy produced, which cannot catch a "
            "disagreement about header layout, sample format or byte order -- "
            "the reader and writer would simply share the mistake."
        ),
        provenance=(
            "The segyio project's test corpus (Equinor). Synthetic content: it "
            "is a small regular cube, not a shot gather, so its trace headers "
            "carry no meaningful source-receiver offsets."
        ),
        licence=(
            "segyio is LGPL-licensed and its README solicits test files under "
            "free licences. Fetched, not vendored."
        ),
    ),
)


def data_dir() -> Path:
    """
    Resolve the directory fetched datasets live in.

    Returns
    -------
    pathlib.Path
        ``$FWAP_REAL_DATA_DIR`` if set, else ``tests/data/real`` under the
        repository root.
    """
    override = os.environ.get(DATA_DIR_ENV)
    if override:
        return Path(override).expanduser()
    return Path(__file__).resolve().parent.parent / DEFAULT_DATA_DIR


def find(name: str) -> RealDataset:
    """
    Look up a dataset by registry name.

    Raises
    ------
    KeyError
        If ``name`` is not registered.
    """
    for dataset in DATASETS:
        if dataset.name == name:
            return dataset
    known = ", ".join(d.name for d in DATASETS)
    raise KeyError(f"unknown dataset {name!r}; known datasets: {known}")


def sha256_of(path: Path) -> str:
    """Return the hex SHA-256 digest of a file, read in chunks."""
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        while chunk := handle.read(_CHUNK):
            digest.update(chunk)
    return digest.hexdigest()


def local_path(dataset: RealDataset, directory: Path | None = None) -> Path:
    """Where ``dataset`` is (or would be) stored locally."""
    return (directory or data_dir()) / dataset.filename


def verify(dataset: RealDataset, directory: Path | None = None) -> bool:
    """
    Check a already-downloaded dataset against its recorded checksum.

    Returns
    -------
    bool
        ``True`` if the file exists and its digest matches.
    """
    path = local_path(dataset, directory)
    return path.is_file() and sha256_of(path) == dataset.sha256


def fetch(
    dataset: RealDataset,
    directory: Path | None = None,
    *,
    force: bool = False,
) -> Path:
    """
    Download one dataset and verify its checksum.

    Parameters
    ----------
    dataset : RealDataset
    directory : pathlib.Path or None
        Destination directory; defaults to :func:`data_dir`.
    force : bool, default False
        Re-download even if a verified copy is already present.

    Returns
    -------
    pathlib.Path
        Path to the verified local file.

    Raises
    ------
    OSError
        If the download fails.
    ValueError
        If the downloaded bytes do not match the recorded SHA-256. The bad file
        is removed rather than left to be silently tested against.
    """
    destination = directory or data_dir()
    destination.mkdir(parents=True, exist_ok=True)
    path = local_path(dataset, destination)

    if path.is_file() and not force:
        if verify(dataset, destination):
            return path
        raise ValueError(
            f"{path} exists but its checksum does not match the registry; "
            "re-run with --force to replace it"
        )

    with urllib.request.urlopen(dataset.url) as response:  # noqa: S310
        payload = response.read()
    path.write_bytes(payload)

    digest = sha256_of(path)
    if digest != dataset.sha256:
        path.unlink(missing_ok=True)
        raise ValueError(
            f"checksum mismatch for {dataset.name}: expected {dataset.sha256}, "
            f"got {digest}. The upstream file may have changed; do not update "
            "the registry hash without checking what changed."
        )
    return path


def format_registry() -> str:
    """Render the registry, licences included, as human-readable text."""
    lines: list[str] = []
    for dataset in DATASETS:
        present = "present" if verify(dataset) else "not fetched"
        lines.append(f"{dataset.name}  [{dataset.kind}]  ({present})")
        lines.append(f"  file      : {dataset.filename}")
        lines.append(f"  url       : {dataset.url}")
        lines.append(f"  tests     : {dataset.what_it_tests}")
        lines.append(f"  provenance: {dataset.provenance}")
        lines.append(f"  licence   : {dataset.licence}")
        lines.append("")
    lines.append(f"destination: {data_dir()}  (git-ignored; never committed)")
    return "\n".join(lines)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Fetch third-party real-world log files for the optional "
            "integration tests. Files are downloaded, never vendored."
        )
    )
    parser.add_argument(
        "--list", action="store_true", help="show the registry and licences"
    )
    parser.add_argument(
        "--fetch",
        metavar="NAME",
        help="dataset to download, or 'all'",
    )
    parser.add_argument(
        "--verify", action="store_true", help="re-check checksums of local files"
    )
    parser.add_argument(
        "--force", action="store_true", help="re-download even if present"
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    """
    Command-line entry point.

    Returns
    -------
    int
        ``0`` on success, ``1`` if a fetch or verification failed.
    """
    args = _build_parser().parse_args(argv)

    if args.verify:
        failed = False
        for dataset in DATASETS:
            ok = verify(dataset)
            print(f"{'OK  ' if ok else 'MISS'}  {dataset.name}")
            failed |= not ok
        return 1 if failed else 0

    if args.fetch:
        targets = DATASETS if args.fetch == "all" else (find(args.fetch),)
        for dataset in targets:
            try:
                path = fetch(dataset, force=args.force)
            except (OSError, ValueError) as exc:
                print(f"FAILED {dataset.name}: {exc}")
                return 1
            print(f"fetched {dataset.name} -> {path}")
        print("\nThese files are third-party and git-ignored. Do not commit them.")
        return 0

    print(format_registry())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
